name: 📖 Feature request
description: File a feature request
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to think about new features!
  - type: checkboxes
    attributes:
      label: Checked the options and documentation
      description: Please make sure that the feature isn't already there.
      options:
      - label: "I double checked and this feature doesn't exist yet."
        required: true
  - type: textarea
    id: idea
    attributes: 
      label: Idea
      description: What is the idea you've got?
      placeholder: I want StatBot to generate world peace.
    validations:
      required: true
